# -*- coding: utf-8 -*-
"""PersonalNotebookManager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKd7hJnhrH7jTlxVDW_KZpUk5gynFucR
"""



"""
Personal Notebook Manager
Console-based notes application
Compatible with Google Colab
** The password is "0000"
"""

# Imported libraries
import json
import os
from datetime import datetime

notes_file = "notes.json"

# ANSI Colors
green = "\033[92m"
red = "\033[91m"
magenta = "\033[35m"
blue = "\033[34m"
reset = "\033[0m"


# Password Login
def login():
    PASSWORD = "0000"
    print(blue + "This notebook is password protected" + reset)

    while True:
        user_input = input("Enter password: ")
        if user_input == PASSWORD:
            print(green + "\n Login successful!\n" + reset)
            break
        else:
            print(red + "Incorrect password! Try again:\n" + reset)


# --------------------- Load notes from file ---------------------

def load_notes():
    if os.path.exists(notes_file):
        with open(notes_file, "r", encoding="utf-8") as f:
            return json.load(f)
    return []



# --------------------- Save notes to file ---------------------

def save_notes(notes):
    with open(notes_file, "w", encoding="utf-8") as f:
        json.dump(notes, f, indent=2, ensure_ascii=False)



# --------------------- Add a new note ---------------------

def add_note(notes):
    title = input("Enter note title: ")
    content = input("Enter note content: ")
    tags = input("Enter tags (comma separated): ").split(",")

    note = {
        "title": title,
        "content": content,
        "tags": [t.strip() for t in tags],
        "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    notes.append(note)
    save_notes(notes)
    print(green + "\n Note added successfully!\n" + reset)


# --------------------- List all notes ---------------------

def list_notes(notes):
    if not notes:
        print(red + "\nNo notes found.\n" + reset)
        return

    print(magenta + "\n------ All Notes ------" + reset)
    for i, note in enumerate(notes, start=1):
        print(f"\n[{i}] {note['title']}")
        print("Date:", note["date"])
        print("Tags:", ", ".join(note["tags"]))
        print("Content:", note["content"])
    print()


# --------------------- Search notes by keyword ---------------------
def search_notes(notes):
    keyword = input("Enter keyword to search: ").lower()
    results = [note for note in notes
               if keyword in note["title"].lower() or keyword in note["content"].lower()]

    if not results:
        print(red + "\nNo matching notes found.\n" + reset)
        return

    print(magenta + "\n------ Search Results ------" + reset)
    for note in results:
        print(f"\nTitle: {note['title']}")
        print("Date:", note["date"])
        print("Tags:", ", ".join(note["tags"]))
        print("Content:", note["content"])
    print()


# --------------------- Filter notes by tag ---------------------
def filter_by_tag(notes):
    tag = input("Enter tag to filter: ").lower()
    results = [note for note in notes if tag in [t.lower() for t in note["tags"]]]

    if not results:
        print(red + "\nNo notes found with this tag.\n" + reset)
        return

    print(magenta + "\n ------ Filter Results ------" + reset)
    for note in results:
        print(f"\nTitle: {note['title']}")
        print("Date:", note["date"])
        print("Tags:", ", ".join(note["tags"]))
        print("Content:", note["content"])
    print()


# --------------------- Sort notes ---------------------
def sort_notes(notes):
    print("""
Sort by:
    (1) Title
    (2) Date
""")

    choice = input("Choose option: ")

    if choice == "1":
        notes.sort(key=lambda x: x["title"].lower())
        print(green + "\n Notes sorted by title!\n" + reset)

    elif choice == "2":
        notes.sort(key=lambda x: x["date"])
        print(green + "\n Notes sorted by date!\n" + reset)

    else:
        print(red + "\nInvalid choice.\n" + reset)

    save_notes(notes)


# --------------------- Edit an existing note ---------------------
def edit_note(notes):
    list_notes(notes)
    try:
        index = int(input("Enter note number to edit: ")) - 1
        if index < 0 or index >= len(notes):
            print(red + "Invalid note number." + reset)
            return
    except ValueError:
        print(red + "Invalid input." + reset)
        return

    note = notes[index]

    new_title = input("New title (press Enter to keep): ")
    new_content = input("New content (press Enter to keep): ")
    new_tags = input("New tags (comma separated, empty to keep): ")

    if new_title:
        note["title"] = new_title
    if new_content:
        note["content"] = new_content
    if new_tags:
        note["tags"] = [t.strip() for t in new_tags.split(",")]

    save_notes(notes)
    print(green + "\n Note updated successfully!\n" + reset)


# --------------------- Delete a note ---------------------
def delete_note(notes):
    list_notes(notes)
    try:
        index = int(input("Enter note number to delete: ")) - 1
        if index < 0 or index >= len(notes):
            print(red + "Invalid note number." + reset)
            return
    except ValueError:
        print(red + "Invalid input." + reset)
        return

    notes.pop(index)
    save_notes(notes)
    print(green + "\n✔ Note deleted successfully!\n" + reset)


# --------------------- Main loop ---------------------
def main():
    login()

    notes = load_notes()

    while True:
        print("""
--------------------- Personal Notebook Manager ---------------------
(1) Add a new note
(2) List all notes
(3) Search notes
(4) Filter by tag
(5) Edit a note
(6) Delete a note
(7) Sort notes
(0) Exit
""")

        choice = input("Choose an option: ")

        if choice == "1":
            add_note(notes)
        elif choice == "2":
            list_notes(notes)
        elif choice == "3":
            search_notes(notes)
        elif choice == "4":
            filter_by_tag(notes)
        elif choice == "5":
            edit_note(notes)
        elif choice == "6":
            delete_note(notes)
        elif choice == "7":
            sort_notes(notes)
        elif choice == "0":
            print(green + "Logged out!" + reset)
            break
        else:
            print(red + "Invalid choice, try again.\n" + reset)


# Run program
if __name__ == "__main__":
    main()